<?php

// --- REQUIRED when using Composer ---
// Load Composer's autoloader. This file is automatically generated by Composer
// in the 'vendor' directory when you install packages.
require __DIR__ . '/vendor/autoload.php';

// Import PHPMailer classes into the global namespace using `use` statements.
// These must be at the top of your script, after the autoloader require.
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;


/**
 * Retrieves a user's email from the database and sends them an email.
 *
 * @param string $username The username of the recipient.
 * @param string $subject The subject of the email.
 * @param string $messageBody The HTML or plain text body of the email.
 * @param bool $isHtml Whether the email body is HTML (defaults to true).
 * @return bool True if the email was sent successfully, false otherwise.
 */
function sendEmailToUser(string $username, string $subject, string $messageBody, bool $isHtml = true): bool
{
    // --- Database Configuration ---
    // !!! IMPORTANT: REPLACE WITH YOUR ACTUAL DATABASE CREDENTIALS !!!
    $dbHost = 'localhost'; // e.g., 'localhost' or '127.0.0.1'
    $dbName = 'senior';
    $dbUser = 'root';
    $dbPass = '';
    $dbCharset = 'utf8mb4';

    // --- SMTP Server Configuration ---
    // !!! IMPORTANT: REPLACE WITH YOUR ACTUAL SMTP CREDENTIALS !!!
    $smtpHost = 'smtp.gmail.com'; // e.g., 'smtp.gmail.com' or 'smtp.mailgun.org'
    $smtpPort = 587; // Common ports: 587 (TLS), 465 (SSL). Check your SMTP provider.
    $smtpUsername = 'medicalcenter028@gmail.com'; // Your email address for SMTP authentication
    $smtpPassword = 'bokq klmq dcaa qzyy'; // Your email password or app-specific password
    // Encryption: Use PHPMailer::ENCRYPTION_STARTTLS for port 587, PHPMailer::ENCRYPTION_SMTPS for port 465
    $smtpEncryption = PHPMailer::ENCRYPTION_STARTTLS;
    $fromEmail = 'medicalcenter028@gmail.com'; // The "From" email address (must often match SMTP username)
    $fromName = 'Medical Center '; // The "From" name

    $userEmail = null;

    // 1. Get user's email from the database
    $dsn = "mysql:host={$dbHost};dbname={$dbName};charset={$dbCharset}";
    $options = [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION, // Report errors as exceptions
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,       // Fetch rows as associative arrays
        PDO::ATTR_EMULATE_PREPARES   => false,                  // Use native prepared statements
    ];

    try {
        $pdo = new PDO($dsn, $dbUser, $dbPass, $options);

        // Prepare a statement to prevent SQL injection
        // Assuming you have a 'users' table with 'username' and 'email' columns
        $stmt = $pdo->prepare("SELECT email FROM users WHERE username = :username LIMIT 1");
        $stmt->bindParam(':username', $username, PDO::PARAM_STR);
        $stmt->execute();

        $user = $stmt->fetch();

        if ($user && !empty($user['email'])) {
            $userEmail = $user['email'];
        } else {
            // Log error or handle case where user/email is not found
            // error_log("User '{$username}' not found or email is missing in the database.");
            // You might want a more user-friendly message or logging mechanism
            echo "Error: User '{$username}' not found or email is missing.\n"; // For testing
            return false;
        }
    } catch (PDOException $e) {
        // Log database connection or query error
        // error_log("Database error: " . $e->getMessage());
         echo "Database error: " . $e->getMessage() . "\n"; // For testing
        return false;
    }

    // If email was not found or database error occurred, stop here
    if (!$userEmail) {
        return false;
    }

    // 2. Send email using SMTP
    // Create a new PHPMailer instance. Passing `true` enables exceptions which we catch below.
    $mail = new PHPMailer(true);

    try {
        // Server settings
        // $mail->SMTPDebug = SMTP::DEBUG_SERVER; // Enable verbose debug output for troubleshooting
        $mail->isSMTP();                                   // Send using SMTP
        $mail->Host         = $smtpHost;                   // Set the SMTP server to send through
        $mail->SMTPAuth     = true;                        // Enable SMTP authentication
        $mail->Username     = $smtpUsername;               // SMTP username (your email address)
        $mail->Password     = $smtpPassword;               // SMTP password (your email password or app password)
        $mail->SMTPSecure   = $smtpEncryption;             // Enable implicit TLS/SSL encryption
        $mail->Port         = $smtpPort;                   // TCP port to connect to

        // Recipients
        $mail->setFrom($fromEmail, $fromName);
        $mail->addAddress($userEmail, $username); // Add a recipient (name is optional)

        // Content
        $mail->isHTML($isHtml);                     
        $mail->Subject = $subject;
        $mail->Body    = $messageBody;

        // Plain text alternative for HTML emails is important for compatibility
        if ($isHtml && empty($mail->AltBody)) {
            // Simple fallback: remove HTML tags
            $mail->AltBody = strip_tags($messageBody);
        } else if (!$isHtml) {
            // If the original message body was plain text, use it for AltBody as well
            $mail->AltBody = $messageBody;
        }


        $mail->send();
        return true;

    } catch (Exception $e) {
        
         echo "Message could not be sent to {$userEmail}. Mailer Error: {$mail->ErrorInfo}\n"; // For testing
        return false;
    }
}

$testUsername = 'ghinwa abo sahyoun'; // Replace with an actual username from your database
$emailSubject = 'Test Email from PHP Script';
$emailBodyHtml = '<h1>Hello ' . htmlspecialchars($testUsername) . '!</h1>
                 <p>This is a <strong>test email</strong> sent via an SMTP server using PHPMailer.</p>
                 <p>Thank you for testing!</p>';
$emailBodyPlain = "Hello " . $testUsername . ",\n\nThis is a plain text test email.\n\nRegards,\nYour App";


// Send an HTML email
echo "Attempting to send HTML email to {$testUsername}...\n";
if (sendEmailToUser($testUsername, $emailSubject . " (HTML)", $emailBodyHtml, true)) {
    echo "HTML email successfully sent to {$testUsername}.\n";
} else {
    echo "Failed to send HTML email to {$testUsername}.\n";
}

// Send a plain text email
echo "Attempting to send Plain Text email to {$testUsername}...\n";
if (sendEmailToUser($testUsername, $emailSubject . " (Plain Text)", $emailBodyPlain, false)) {
    echo "Plain text email successfully sent to {$testUsername}.\n";
} else {
    echo "Failed to send plain text email to {$testUsername}.\n";
}




// function sendEmailToSecretary(string $username, string $subject, string $messageBody, bool $isHtml = true): bool
// {
//     // --- Database Configuration ---
//     $dbHost = 'localhost';
//     $dbName = 'senior';
//     $dbUser = 'root';
//     $dbPass = '';
//     $dbCharset = 'utf8mb4';

//     // --- SMTP Server Configuration ---
//     $smtpHost = 'smtp.gmail.com';
//     $smtpPort = 587;
//     $smtpUsername = 'medicalcenter028@gmail.com';
//     $smtpPassword = 'bokq klmq dcaa qzyy';
//     $smtpEncryption = PHPMailer::ENCRYPTION_STARTTLS;
//     $fromEmail = 'medicalcenter028@gmail.com';
//     $fromName = 'Medical Center';

//     $secretaryEmail = null;

//     // 1. Get secretary's email from the database
//     $dsn = "mysql:host={$dbHost};dbname={$dbName};charset={$dbCharset}";
//     $options = [
//         PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
//         PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
//         PDO::ATTR_EMULATE_PREPARES   => false,
//     ];

//     try {
//         $pdo = new PDO($dsn, $dbUser, $dbPass, $options);

//         $stmt = $pdo->prepare("SELECT email FROM secretary WHERE fullname = :username LIMIT 1");
//         $stmt->bindParam(':username', $username, PDO::PARAM_STR);
//         $stmt->execute();

//         $secretary = $stmt->fetch();

//         if ($secretary && !empty($secretary['email'])) {
//             $secretaryEmail = $secretary['email'];
//         } else {
//             echo "Error: Secretary '{$username}' not found or email is missing.\n";
//             return false;
//         }
//     } catch (PDOException $e) {
//         echo "Database error: " . $e->getMessage() . "\n";
//         return false;
//     }

//     if (!$secretaryEmail) {
//         return false;
//     }

//     // 2. Send email using PHPMailer
//     $mail = new PHPMailer(true);

//     try {
//         $mail->isSMTP();
//         $mail->Host       = $smtpHost;
//         $mail->SMTPAuth   = true;
//         $mail->Username   = $smtpUsername;
//         $mail->Password   = $smtpPassword;
//         $mail->SMTPSecure = $smtpEncryption;
//         $mail->Port       = $smtpPort;

//         $mail->setFrom($fromEmail, $fromName);
//         $mail->addAddress($secretaryEmail, $username);

//         $mail->isHTML($isHtml);
//         $mail->Subject = $subject;
//         $mail->Body    = $messageBody;

//         $mail->AltBody = $isHtml ? strip_tags($messageBody) : $messageBody;

//         $mail->send();
//         return true;

//     } catch (Exception $e) {
//         echo "Message could not be sent to {$secretaryEmail}. Mailer Error: {$mail->ErrorInfo}\n";
//         return false;
//     }
// }

// function sendEmailToDoctor(string $username, string $subject, string $messageBody, bool $isHtml = true): bool
// {
//     // --- Database Configuration ---
//     $dbHost = 'localhost';
//     $dbName = 'senior';
//     $dbUser = 'root';
//     $dbPass = '';
//     $dbCharset = 'utf8mb4';

//     // --- SMTP Configuration ---
//     $smtpHost = 'smtp.gmail.com';
//     $smtpPort = 587;
//     $smtpUsername = 'medicalcenter028@gmail.com';
//     $smtpPassword = 'bokq klmq dcaa qzyy';
//     $smtpEncryption = PHPMailer::ENCRYPTION_STARTTLS;
//     $fromEmail = 'medicalcenter028@gmail.com';
//     $fromName = 'Medical Center';

//     $doctorEmail = null;

//     $dsn = "mysql:host={$dbHost};dbname={$dbName};charset={$dbCharset}";
//     $options = [
//         PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
//         PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
//         PDO::ATTR_EMULATE_PREPARES   => false,
//     ];

//     try {
//         $pdo = new PDO($dsn, $dbUser, $dbPass, $options);

//         $stmt = $pdo->prepare("SELECT email FROM doctors WHERE fullname = :username LIMIT 1");
//         $stmt->bindParam(':username', $username, PDO::PARAM_STR);
//         $stmt->execute();

//         $doctor = $stmt->fetch();

//         if ($doctor && !empty($doctor['email'])) {
//             $doctorEmail = $doctor['email'];
//         } else {
//             echo "Error: Doctor '{$username}' not found or email is missing.\n";
//             return false;
//         }
//     } catch (PDOException $e) {
//         echo "Database error: " . $e->getMessage() . "\n";
//         return false;
//     }

//     if (!$doctorEmail) {
//         return false;
//     }

//     $mail = new PHPMailer(true);

//     try {
//         $mail->isSMTP();
//         $mail->Host       = $smtpHost;
//         $mail->SMTPAuth   = true;
//         $mail->Username   = $smtpUsername;
//         $mail->Password   = $smtpPassword;
//         $mail->SMTPSecure = $smtpEncryption;
//         $mail->Port       = $smtpPort;

//         $mail->setFrom($fromEmail, $fromName);
//         $mail->addAddress($doctorEmail, $username);

//         $mail->isHTML($isHtml);
//         $mail->Subject = $subject;
//         $mail->Body    = $messageBody;
//         $mail->AltBody = $isHtml ? strip_tags($messageBody) : $messageBody;

//         $mail->send();
//         return true;

//     } catch (Exception $e) {
//         echo "Message could not be sent to {$doctorEmail}. Mailer Error: {$mail->ErrorInfo}\n";
//         return false;
//     }
// }

// require 'vendor/autoload.php'; // Ensure PHPMailer is included

// Include your functions here or require them if they are in a separate file
// require_once 'email_functions.php';

// Test email for Secretary Heba Kareem
$secretarySuccess = sendEmailToSecretary(
    'heba kareem',
    'Test Email to Secretary',
    '<b>Hello Heba!</b><br>This is a test email sent to the secretary.',
    true
);

// Test email for Doctor James Charles
$doctorSuccess = sendEmailToDoctor(
    'James Charles',
    'Test Email to Doctor',
    '<b>Hello Dr. James!</b><br>This is a test email sent to the doctor.',
    true
);

// Output result
echo $secretarySuccess ? "Email sent to Heba Kareem successfully.\n" : "Failed to send email to Heba Kareem.\n";
echo $doctorSuccess ? "Email sent to James Charles successfully.\n" : "Failed to send email to James Charles.\n";


// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;
?>